spring:
  application:
    name: restaurant-authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_users
    username: root
    password: password
  liquibase:
    change-log: classpath:db/prod/changelog.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8990/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8083
  error:
    include-stacktrace: never

jwt:
  audience: Restaurant authoriaztaion
  access:
    expiration: 120
    signing-key: 2K8hHJdVgyPYh8OTnYPIl9gBb05wLTATqv0Z623jH3wokVwkqGM10i/m10Gof5ry
  refresh:
    expiration: 10080
    signing-key: bQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(