spring:
  application:
    name: restaurant-authentication-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: user
    password:
    driver-class-name: org.h2.Driver

jwt:
  audience: Restaurant authentication
  access:
    expiration: 120
    signing-key: 2K8hHJdVgyPYh8OTnYPIl9gBb05wLTATqv0Z623jH3wokVwkqGM10i/m10Gof5ry
  refresh:
    expiration: 10080
    signing-key: bQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(