spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/restaurant_users
    username: root
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8990/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8083

jwt:
  expiration: 7 #days after jwt expires
  signing-key: 2K8hHJdVgyPYh8OTnYPIl9gBb05wLTATqv0Z623jH3wokVwkqGM10i/m10Gof5ry
