eureka:
  client:
    service-url:
      defaultZone: http://localhost:8990/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8082
spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: someGmailUser@gmail.com
    password: passToSomeGmailUser
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

restaurant:
  restaurantName: Restauracja Spring